# Generated by Django 5.1.1 on 2024-09-28 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1024)),
                ('metadata', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ContextDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('tax_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xml_generator.taxform')),
            ],
        ),
        migrations.CreateModel(
            name='TaxFormInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('user_designation', models.CharField(max_length=20, null=True)),
                ('user_id', models.UUIDField(null=True)),
                ('data', models.JSONField()),
                ('xml', models.TextField()),
                ('status', models.CharField(choices=[('n', 'e'), ('v', 'a'), ('p', 'o')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_interaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.interaction')),
                ('tax_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xml_generator.taxform')),
            ],
        ),
        migrations.CreateModel(
            name='TaxFormValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('xsd', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_till', models.DateField(null=True)),
                ('tax_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='xml_generator.taxform')),
            ],
        ),
    ]
